baseURL = 'https://poyen16.github.io/iOSclub_hugo/'
languageCode = 'zh-tw'
title = 'My Blog'
theme = 'ananke'
contentDir = "content"

[taxonomies]
    tag = 'tags'
    category = 'categories'
    disableKinds = ['taxonomyTerm']
