baseURL = 'https://poyen16.github.io/iOSclub_hugo/'
languageCode = 'zh-tw'
title = 'My Blog'
theme = 'ananke'
contentDir = "content"
[params]
background_color_class = "bg-blue"
recent_posts_number = 5

[taxonomies]
    tag = 'tags'
    category = 'categories'
    disableKinds = ['taxonomyTerm']


