baseURL = 'https://poyen16.github.io/iOSclub_hugo/'
languageCode = 'zh-tw'
title = 'My Blog'
theme = 'ananke'
contentDir = "content"
[params]
background_color_class = "bg-blue"

[taxonomies]
    tag = 'tags'
    category = 'categories'
    disableKinds = ['taxonomyTerm']

{{ $pages := .Pages }}
{{ if .IsHome }}
{{ $pages = .Site.RegularPages }}
{{ end }}
{{ $paginator := .Paginate $pages }}
